version: '3.9'

services:
  db:
    image: mongo:latest
    container_name: db
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    image: ghcr.io/grantassist/backend-api:latest
    container_name: backend
    ports:
      - '3000:3000'
    env_file:
      - backend.env
    depends_on:
      - db

  frontend:
    image: ghcr.io/grantassist/client:latest
    container_name: frontend
    ports:
      - '3001:3001'
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:
  